### ISSUE TITLE
Scrap and Merchant Plus Tab in the Same Spot

### ISSUE THREAD

**Issue by wheatbread** [kstange/MerchantPlus#5]
Hi, thank you for this great addon!

Came to report that Scrap and Merchant Plus tab are in the same spot.  

https://i.imgur.com/MGPvoqD.png

**Comment by kstange** [comment]
There are a couple different issues here that I can see.

Both addons adding tabs to the window in a similar way because if we try to put them into the tab group with the real merchant frame it will cause taint (addon blocked) errors, but we don't really have a way to detect that other addons are doing the same thing.

There's also and issue with switching between the Scrap and Merchant Plus tabs where the window layout won't get updated properly.  This similarly a case of not realizing that the other addon exists.

I will look into both issues, but I can't promise anything.

**Comment by kstange** [comment]
I took a look at this and the author of Scrap actually created a library for managing custom tabs separate from their addon.  My solution works in a vacuum, but this should provide a solution to the problem. I'll try to adapt Merchant Plus to use this library soon.

**Comment by tusharsaxena** [comment]
Had the same issue, my workaround was to use [Dejunk](https://www.curseforge.com/wow/addons/dejunk) instead :)

**Comment by kstange** [comment]
I finally got around to trying to implement this, but library used by Scrap is actually incomplete, contrary to its own documentation, and I can't accomplish what I need to be able to do to use it, so I'm not going to be able to do this for now.
